#!/bin/bash

for f in *.xsd; do
    if grep 'Event"' $f | grep complexType | grep -qv abstract; then
        echo "<jaxb:bindings schemaLocation=\"$f\" node=\"/xs:schema\">"

	grep 'Event"' $f | grep complexType | grep -v abstract | \
	        awk -F\" '{printf("<jaxb:bindings node='\''xs:complexType[@name=\"%s\"]'\''>\n<annox:annotateClass>@javax.xml.bind.annotation.XmlRootElement(name=\"%s\")</annox:annotateClass>\n</jaxb:bindings>\n", $2, $2)}'
       echo "</jaxb:bindings>"
   fi
done
